<?php

function alltickets_preprocess_block__alltickets_header(array &$variables) {
    // Verificar si existe una variable de sesión
    if (isset($_SESSION['IDuser']) && $_SESSION['IDuser'] !== '') {
        // Obtener el valor de la variable de sesión
        $valorSesion = $_SESSION['IDuser'];
    } else {
        $valorSesion = '';
    }

    // Pasar el valor a la plantilla
    $variables['email'] = $valorSesion;
}